### ISSUE TITLE
Shows Blank Screen

### ISSUE THREAD

**Issue by sophin123** [champ3oy/MobileView#1]
Hi, 
Just got some speck issues.
It shows nothing but black screen. No loading indicator, No warning message, No feedback. Do you have any idea what's going on?
I have attached the screenshot. 

![Screenshot](https://user-images.githubusercontent.com/46114283/151728180-2cbee501-30b5-4e57-b396-effac190cce8.PNG)

BTW. Thank you for such project :)

**Comment by couscousbzh** [comment]
Hi, same same. Looks great tool, but for now, useless with a black screen.
Tks anyway

**Comment by Carsonthemonkey** [comment]
Same issue for me, on windows 10

**Comment by waleedrana777** [comment]
Same issue on windows 10 in 2023, still not fixed, kindly remove the extension from marketplace if it you don't want to fix! Great potential in the tool but not maintained!

**Comment by saulojoab** [comment]
Also happens on my M1 Macbook Pro

**Comment by salesrocketdev** [comment]
Same issue on windows 11 21H2 :(

**Comment by Sachabbbbbbbbbbbb** [comment]
Même problème sous Windows 10

**Comment by carlospunkk** [comment]
há tela está preta no linux ubuntu também , sabe como resolver.?

**Comment by chrysos** [comment]
On Mac too, I enter localhost and it rewrites it to 127.0.0.1, in some projects this entry does not work.

**Comment by camivand4** [comment]
Same issue here. Windows 11 vscode version 1.85.1

**Comment by jpcmf** [comment]
> On Mac too, I enter localhost and it redirect it to 127.0.0.1, in some projects this entry does not work.

Same issue here.

**Comment by Sacha338** [comment]
Now, you can run your app on an Ios simulator with expo : https://stackoverflow.com/questions/50778011/building-expo-app-for-ios-with-windows

**Comment by JudahIwuchukwu** [comment]
Same,same issue here!!!!!!!

**Comment by champ3oy** [comment]
Update and try again and make sure your website/app is actually rendering something to the page. Thank you

**Comment by sanukadevx** [comment]
hi this issue is back again i think. can't see anything. just a blank screen

**Comment by Duhell** [comment]
First it works, having fun using it. Now, same issue.
