### ISSUE TITLE
Can this support VUE?

### ISSUE THREAD

**Issue by yatayork** [champ3oy/MobileView#6]

**Comment by champ3oy** [comment]
Yes, this supports vue. just spun up the vue server and copy the localhost url in to MobileView

**Comment by yatayork** [comment]
done, thanks very much  this extension help me a lot 
If some one who use Vite and want to use this extension for mobileView
need to go vite.config.js  and  add sever object with host:"0.0.0.0"  run dev 
and use network url that mobileView need ,it will show the view 
when I use localhost it blank ,Idk why but use network host is success , thanks again
